site_name: 张宇的网络日志
theme:
  name: material
  palette:
    scheme: slate
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.highlight
  plugins:
    - search:
        lang: zh
        separator: '[\s\u200b\-]'
