site_name: 张宇的
theme:
  name: material
  language: zh
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.highlight
  plugins:
    - search:
        lang: zh
        separator: '[\s\u200b\-]'
    - blog:
        post_url_date_format: yyyy-MM-dd
